In [5]:

import numpy as np

a = np.array([0, 1, 2])
b = np.array([5, 5, 5])

a + b


array([5, 6, 7])

In [3]:
a * b

array([ 0,  5, 10])

In [6]:
a + 5 # == a + [5, 5, 5]

array([5, 6, 7])

In [7]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [13]:

a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

print(a)
print(b)


[0 1 2]
[[0]
 [1]
 [2]]


In [14]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [16]:
#
# Rule 1: 
# If the two arrays differ in their number of dimensions, 
# the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
#
# Rule 2: 
# If the shape of the two arrays does not match in any dimension, 
# the array with shape equal to 1 in that dimension is stretched to match the other shape.
#
# Rule 3: 
# If in any dimension the sizes disagree and neither is equal to 1, an error is raised.
#

In [22]:
M = np.ones((2, 3))
a = np.arange(3)

print(M)
print()
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]

[0 1 2]


In [23]:
# M.shape = (2, 3)
# a.shape = (3,)

# By rule 1 :

# M.shape -> ( 2, 3 )
# a.shape -> ( 1, 3 ) == [0, 1, 2]

# By rule 2 :

# M.shape -> ( 2, 3 )
# a.shape -> ( 2, 3 ) == [ [0, 1, 2], [0, 1, 2] ]

In [26]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [27]:
# Example 2

a = np.arange(3).reshape((3, 1))
b = np.arange(3)

print(a)
print()
print(b)

[[0]
 [1]
 [2]]

[0 1 2]


In [28]:
# a.shape = (3, 1)
# b.shape = (3,)

# By rule 1 :

# a.shape -> ( 3, 1 )
# b.shape -> ( 1, 3 )

# By rule 2 :

# a.shape -> ( 3, 3 )
# b.shape -> ( 3, 3 )

#         [0 0 0]   [0 1 2]
# a + b = [1 1 1] + [0 1 2]
#         [2 2 2]   [0 1 2]

a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [29]:
# Example 3

M = np.ones((3, 2))
a = np.arange(3)

print(M)
print()
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[0 1 2]


In [44]:
# M.shape = (3, 2)
# a.shape = (3,)

# By rule 1 :

# M.shape -> ( 3, 2 )
# a.shape -> ( 1, 3 )

# By rule 2 :

# M.shape -> ( 3, 2 )
# a.shape -> ( 3, 3 )

#===========================

a[:, np.newaxis].shape

(3, 1)

In [51]:
a[:, np.newaxis]

array([[0],
       [1],
       [2]])

In [52]:
M + a[:, np.newaxis]

array([[1., 1.],
       [2., 2.],
       [3., 3.]])