In [218]:

import numpy as np

x1 = np.array( [ 5, 0, 3, 8, 7, 9, 11, 55, 1701 ] )  # One-dimensional array

x2 = np.array( [ [ 1, 3, 5, 7 ],
                 [ 2, 4, 6, 8 ], 
                 [ 4, 6, 7, 3 ] ] )  # Two-dimensional array

x3 = np.array( [ [ [ 1, 2, 3 ],    [ 4, 5, 6 ]    ],
                 [ [ 7, 8, 9 ],    [ 10, 11, 12 ] ],
                 [ [ 22, 33, 44 ], [ 55, 66, 77 ] ] ] )  # Three-dimensional array

In [219]:
'''
============================================================================================
1. Element indexing
'''

x1

array([   5,    0,    3,    8,    7,    9,   11,   55, 1701])

In [271]:
x1[0]

11

In [221]:
x2[0,0]

1

In [222]:
x3[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [223]:
x1[-1] # To index from the end of the array, you can use negative indices

1701

In [224]:
x2[2,-1]

3

In [225]:
x2[2,2] = 77.9 # if you attempt to insert a floating-point value to an integer array, the value will be silently truncated !
x2

array([[ 1,  3,  5,  7],
       [ 2,  4,  6,  8],
       [ 4,  6, 77,  3]])

In [228]:
'''
============================================================================================
2. Array Slicing: Accessing Subarrays
'''

# x[start:stop:step]

x1[:3] # first 3 elements

array([5, 0, 3])

In [227]:
x1[:-3] # all elements till last 3

array([5, 0, 3, 8, 7, 9])

In [140]:
x1[3:] # elements after index 3

array([   8,    7,    9,   11,   55, 1701])

In [237]:
x1[3:6]  # middle sub-array

array([8, 7, 9])

In [238]:
x3[:1] 

array([[[1, 2, 3],
        [4, 5, 6]]])

In [239]:
x1[::3]  # every 3d element

array([ 5,  8, 11])

In [240]:
x1[1::2]  # every 2nd element, starting at index 1

array([ 0,  8,  9, 55])

In [241]:
x2[::2,::2] # every 2nd y, every 2nd x

array([[ 1,  5],
       [ 4, 77]])

In [242]:
# inverse situation :
x1[::-2]  # all 2nd elements, reversed

array([1701,   11,    7,    3,    5])

In [243]:
x1 = np.array( [ 5, 0, 3, 8, 7, 9, 11, 55, 1701 ] )  # One-dimensional array

x1[5::-2]  # every 2nd from 6th element to 0

array([9, 8, 0])

In [244]:
x2[:2, ::2]  # all rows till 3d , every 2nd column

array([[1, 5],
       [2, 6]])

In [245]:
x1[1:6:2] # every 2nd from 1st to 7th (not included )

array([0, 8, 9])

In [246]:
# Accessing array rows and columns

x2[:,3]

array([7, 8, 3])

In [247]:
x2_sub = x2[:2, :2]
x2_sub

array([[1, 3],
       [2, 4]])

In [248]:
'''
============================================================================================
3. Array logic indexing
'''
arr = np.array( [ 11, 13, 33, 45, 1, 55, 90, 7 ] )

In [249]:
mask = arr < 10

arr[ mask ]


array([1, 7])

In [250]:
mask

array([False, False, False, False,  True, False, False,  True])

In [251]:
x2 = np.array( [ [ 1, 3, 5, 7 ],
                 [ 2, 4, 6, 8 ], 
                 [ 4, 6, 7, 3 ] ] )  # Two-dimensional array
mask2 = x2 < 6

x2[ mask2 ]

array([1, 3, 5, 2, 4, 4, 3])

In [252]:
mask2[:,1]

array([ True,  True, False])

In [253]:
x2[ mask2[:,1] ]

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [254]:
x3 = np.array( [ [ [ 0,  1,  2,  3,  4  ], [ 5,  6,  7,  8,  9  ], [ 10, 11, 12, 13, 14 ] ],
                 [ [ 15, 16, 17, 18, 19 ], [ 20, 21, 22, 23, 24 ], [ 25, 26, 27, 28, 29 ] ] ] )

b = np.array( [ [ True, True, False ], 
                [ False, True, True ] ] )

x3[ b ]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [260]:
'''
============================================================================================
4. Fancy Indexing
'''

x1 = np.array( [ 11, 13, 33, 45, 1, 55, 90, 7 ] )

ind = [3, 7, 4]

x1[ ind ]

array([45,  7,  1])

In [265]:
ind = np.array([[1, 2],
                [0, 5],
                [4, 2]])

x1[ind]

array([[13, 33],
       [11, 55],
       [ 1, 33]])

In [268]:
x2 = np.array( [ [ 1, 3, 5, 7 ],
                 [ 2, 4, 6, 8 ], 
                 [ 4, 6, 7, 3 ] ] )  # Two-dimensional array


row = np.array([0, 1, 2])
col = np.array([0, 1, 2])

x2[row, col]


array([1, 4, 7])

In [269]:
x2 [row[:, np.newaxis], col]

array([[1, 3, 5],
       [2, 4, 6],
       [4, 6, 7]])